# Generated by Django 5.2.5 on 2025-08-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(max_length=100)),
                ('chai_height', models.FloatField()),
                ('froth_height', models.FloatField()),
                ('chai_to_froth_ratio', models.FloatField()),
                ('bubble_count', models.IntegerField()),
                ('roast', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
