# Generated by Django 5.2.5 on 2025-08-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairesult',
            name='chai_height',
        ),
        migrations.RemoveField(
            model_name='chairesult',
            name='chai_to_froth_ratio',
        ),
        migrations.RemoveField(
            model_name='chairesult',
            name='froth_height',
        ),
        migrations.RemoveField(
            model_name='chairesult',
            name='roast',
        ),
        migrations.AddField(
            model_name='chairesult',
            name='chai_teaspoons',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='chairesult',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chairesult',
            name='bubble_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chairesult',
            name='device_uuid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
